### PR TITLE
Rewrite empty fields.json to fix crash

### PR DESCRIPTION
**Pull request by maple-buice**
## Description and Context

If fields.json is empty, append '[]\n'.
The most likely scenario is that the file has just been created, and current state is that it fails validation and `hs watch` crashes out with a long error message.

This change is being made to address an issue documented internally, link is available upon request in slack.

### CODE REVIEW

**Comment by maple-buice** [comment]
FYI the commit hook forced me to fix prettier errors, so those are included as well. The only real changes are to `lib/cms/watch.ts`.

**Comment by kemmerle** [comment]
@maple-buice, we've had issues with prettier in this repo in the past. Could you hold off on merging until we can talk this over with my team?

**Review by camden11 — APPROVED** [review]

**Comment by brandenrodgers** [comment]
@jsines just double checking before merging. Are these changes still ok to merge in?

**Comment by jsines** [comment]
Yep seems fine!

**Comment by joe-yeager** [comment]
@maple-buice - I just wanted to check in and see if this PR is still needed?

**Comment by joe-yeager** [comment]
Closing this as it seems inactive

**Pull request closed without merging**
